Datavault bulk predictor
innodatalabs/ilabs.client pull request #7
Opened 2019-01-28 12:10 UTC by chinmaygadkari7

2019-02-06 13:17 UTC, mkroutikov requested changes
Minor

2019-02-06 13:17 UTC, mkroutikov commented on ilabs/client/ilabs_api.py
> +        self.URL_PREDICT_ = self.URL_API_BASE + '/prediction/{domain}/{collection}/{name}'
better name, please. Maybe `PREDICT_DATAVAULT`, not `PREDICT_`

2019-02-06 13:17 UTC, mkroutikov commented on ilabs/client/test/test_ilabs_api.py
> +                content_type='test/test', query=None)
not needed change, as query=None is the default

2019-02-07 11:21 UTC, mkroutikov submitted a review, later dismissed
Looks good

2019-02-07 11:28 UTC, chinmaygadkari7 commented
@mkroutikov Version bump to 0.2.6?

2019-02-07 11:41 UTC, mkroutikov commented
Yes, please. After this is merged, please kill the obsolete PR and branches

2019-02-07 12:24 UTC, mkroutikov approved these changes
:)

2019-02-07 13:00 UTC, merged